plugins {
  id 'java-library'
}

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

version = rootProject.version
def appName = rootProject.ext.appName

def generatedResourcesDir = "$buildDir/generated/resources"

tasks.register('generateVersionProperties') {
  def versionFile = file("$generatedResourcesDir/version.properties")
  inputs.property("version", project.version)
  outputs.file(versionFile)

  doLast {
    file(generatedResourcesDir).mkdirs()
    versionFile.text = """\
appName=${appName}
version=${project.version}
""".stripIndent()
  }
}

sourceSets {
  main {
    resources {
      srcDir generatedResourcesDir
    }
  }
}

processResources.dependsOn generateVersionProperties


dependencies {
  api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "org.apache.groovy:groovy-all:$groovyVersion"

  // Netty core
  api 'io.netty:netty-all:4.2.2.Final'

  testImplementation 'org.junit.jupiter:junit-jupiter-api:4.13.2'
  testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:4.13.2'
  testImplementation 'org.apiguardian:apiguardian-api:1.1.2' // Explicitly include this

  if (enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}
